### ISSUE TITLE
How to expand the width of the line of the post?

### ISSUE THREAD

**Issue by binlidaily** [dyndna/lanyon-plus#18]
I use Chinese to write post, the width of line of the post is not that beautiful, so I wanna change the width. I am a newbie, could you please tell me how to do it?

**Comment by binlidaily** [comment]
![image](https://user-images.githubusercontent.com/5987437/34460864-79a9b58a-ee56-11e7-8a22-0f3670da8e6b.png)

**Comment by dyndna** [comment]
You can expand container max-width in `public/css/style.min.css`. I would not expand it beyond 48rem as theme may not show up well in mobile/tablet devices.


```css
  .container {
        max-width: 48rem;
    }
```

**Comment by binlidaily** [comment]
Thank you for your response!

There are a lot of settings with `.container{max-width: 48rem;}`, I don't know change witch one, or I should change all of it?

My solution is that, I add `style` to a new post manually.

```
style: |
  .container {
        max-width: 44rem;
    } 
```
However, this can not deal with the home page of my blog. Now, I don't know how to change the width of my home page. Maybe I also should find the right place in `public/css/style.min.css` to change the `max-width`?
