### ISSUE TITLE
Share Buttons don't show in the newest Chrome and Opera on Windows 7

### ISSUE THREAD

**Issue by ghost** [dyndna/lanyon-plus#7]
Shares buttons in [`meta_info.html`](https://github.com/dyndna/lanyon-plus/blob/master/_includes/meta_info.html)  works well in all browers on OSX. 

But today I find they can't show in the latest Chrome (53.0.2785.116 m) and Opera (41.0.2353.10) on Windows 7.

Please help solving this problem. Thanks!

**Comment by dyndna** [comment]
Do not know about Opera but I have current Chrome stable, 53.0.2785.143 (64-bit) on OS X. I do not see an issue with share buttons, https://dyndna.github.io/lanyon-plus/blog/2013/01/01/example-content/ This could be a temporary issue if font awesome server was not up for that moment. Reopen this issue with link to your webpage if you still have issue with share buttons.

Thanks
