### ISSUE TITLE
_layouts/post.html - Warning from liquid syntax

### ISSUE THREAD

**Issue by LordAmit** [dyndna/lanyon-plus#8]
Hi,
The current post.html file throws lots of warnings in the form of liquid syntax error when built. 

For example, 
```
{% assign moddate = page.modified | date_to_string %}
    {% assign pgdate = page.date | date_to_string %}
    {% unless moddate == pgdate | date_to_string %}
```
Throws,
```  
Liquid Warning: Liquid syntax error (line 14): Expected end_of_string but found pipe in "moddate == pgdate | date_to_string" in /_layouts/post.html                                                                                                                                                   
```

So I was checking, and it seems like both `moddate` and `pgdate` are being filtered using `date_to_string`. Additionally, at the `unless` section, these are being compared for equality; while pgdate is being filtered again.

I am not exactly familiar with liquid syntax, but it seems like filtering should not be necessary while comparing - since both are already storing strings in filtered format. Perhaps, it should be something like: 

```
{% assign moddate = page.modified | date_to_string %}
    {% assign pgdate = page.date | date_to_string %}
    {% unless moddate == pgdate %}
```
This also gets rid of the warning, but I am not sure if it creates any bug / issues in any other section.
Let me know what you think, please.

**Comment by dyndna** [comment]
Thanks for taking time to look at these errors and fixing them. It was wrong piping on my end and should not create any bug.

**Comment by LordAmit** [comment]
Was really annoyed with all those warnings showing up :p
